list(
  rd_family_title = list(admin        = "Other administration functions:",
                         augment      = "Other referendum data augmentation functions:",
                         s3           = "Other AWS S3-compatible object storage functions:",
                         data         = "Other data functions:",
                         aux_data     = "Other auxiliary data:",
                         metadata     = "Other referendum metadata functions:",
                         neon         = "Other Neon.tech functions:",
                         nocodb       = "Other NocoDB functions",
                         pg           = "Other PostgreSQL functions",
                         postgrest    = "Other PostgREST functions",
                         prettify     = "Other functions to prettify names:",
                         sudd         = "Other sudd.ch scraping functions:",
                         tabulate     = "Other tabulation functions:",
                         topics       = "Other referendum topic functions:",
                         transform    = "Other referendum data transformation functions:",
                         unnest       = "Other variable unnesting functions:",
                         url_assembly = "Other URL assembly functions:",
                         visualize    = "Other visualization functions:")
)
