# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/c2d.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literature programming approach used applying the R Markdown format.

utils::globalVariables(names = c(".",
                                 "items"))

.onLoad <- function(libname, pkgname) {
  pkgpins::clear(pkg = pkgname,
                 max_age = getOption("c2d.max_cache_lifespan",
                                     default = "30 days"))
}

.onUnload <- function(libpath) {
  pkgpins::deregister(pkg = pkg)
}

pkg <- utils::packageName()

httr_config <- function() {
  
  httr::config(cainfo = system.file("certs", "3479778542.crt",
                                    package = pkg,
                                    mustWork = TRUE))
}

#' Test C2D API availability
#'
#' Checks if the C2D API server is online and operational.
#'
#' @param quiet Whether to suppress printing a warning in case the API is unavailable.
#'
#' @return A logical scalar.
#' @export
is_online <- function(quiet = FALSE) {
  
  result <- FALSE
  response <- rlang::with_handlers(.expr = httr::RETRY(verb = "GET",
                                                       url = "https://services.c2d.ch/health",
                                                       config = httr_config(),
                                                       times = 5L),
                                   error = ~ paste0("Error: ", .x$message))
  
  if (class(response) == "response") {
    
    response %<>% httr::content(as = "parsed",
                                encoding = "UTF-8")
    
    if (response == "OK") {
      result <- TRUE
      
    } else if (checkmate::assert_flag(quiet)) {
      warning(glue::glue("C2D API server responded with '{response}'"),
              call. = FALSE,
              immediate. = TRUE)
    }
  }
  
  result
}

#' Get referendum data
#'
#' Downloads the complete data about all referendums covered by the C2D Database.
#'
#' Currently, this function only allows to download the C2D referendums database in its entirety.
#'
#' @param use_cache `r pkgsnip::param_label("use_cache")`
#' @param cache_lifespan `r pkgsnip::param_label("cache_lifespan")`
#'
#' @return `r pkgsnip::return_label("data")`
#' @export
referendums <- function(use_cache = TRUE,
                        cache_lifespan = "1 week") {
  
  pkgpins::with_cache(.fn = ~ {
    
    # retrieve data
    data <-
      httr::RETRY(verb = "GET",
                  url = "https://services.c2d.ch/referendums",
                  query = list(mode = "stream",
                               format = "json"),
                  config = httr_config(),
                  times = 5L) %>%
      httr::content(as = "parsed") %$%
      items %>%
      # wrap all array fields in another list level for subsequent conversion to tibble
      purrr::map(.f = ~ .x %>% purrr::modify_if(.p = ~ length(.x) != 1L,
                                                .f = ~ list(.x))) %>%
      # convert to tibble
      dplyr::bind_rows()
    
    # check integrity
    ## ensure there's always exactly *one* `oid` per row
    ids <- data$`_id` %>% purrr::map(length)
    
    if (length(unique(names(ids))) != 1L ||
        !"$oid" %in% unique(names(ids)) ||
        any(purrr::flatten_int(unique(ids))) != 1L) {
      
      rlang::abort("Unexpected ID fields detected. Please debug.")
    }
    
    ## ensure `oid`s are unique
    if (data$`_id` %>%
        purrr::flatten_chr() %>%
        unique() %>%
        length() %>%
        magrittr::equals(nrow(data)) %>%
        magrittr::not()) {
      
      rlang::abort("Duplicated `oid`s detected. Please debug.")
    }
    
    # tidy data
    data %<>%
      dplyr::rename(id = `_id`) %>%
      # unnest `categories` (don't need to be nested)
      tidyr::unnest_wider(col = context) %>%
      tidyr::unnest_wider(col = categories) %>%
      tidyr::unnest_wider(col = title,
                          names_sep = "_") %>%
      dplyr::mutate(id = purrr::flatten_chr(id),
                    created_on = purrr::flatten_dbl(created_on),
                    # flatten unnecessarily convoluted list columns
                    dplyr::across(c(action,
                                    excluded_topics,
                                    special_topics,
                                    tags),
                                  ~ .x %>% purrr::map(unlist)),
                    # replace empty lists with `NULL` in list columns
                    dplyr::across(where(is.list),
                                  ~ dplyr::case_when(.x %>% purrr::map_lgl(~ length(.x) == 0L) ~ list(NULL),
                                                     TRUE ~ .x)),
                    # use explicit NA values
                    dplyr::across(where(is.integer),
                                  ~ dplyr::if_else(.x == -1L, NA_integer_, .x)),
                    dplyr::across(where(is.character),
                                  ~ dplyr::if_else(.x == "", NA_character_, .x))) %>%
      # reorder columns
      dplyr::relocate(id,
                      draft, # TODO: Find out what exactly `TRUE` means here! Maybe we should filter them out?
                      country_code,
                      country_name,
                      canton,
                      municipality,
                      level,
                      institution,
                      date,
                      created_on,
                      starts_with("title_"),
                      total_electorate,
                      citizens_abroad,
                      votes_yes,
                      votes_no,
                      votes_empty,
                      votes_invalid,
                      votes_per_canton,
                      result,
                      committee_name,
                      number, # TODO: Find out what this is!
                      vote_object,
                      author_of_the_vote_object,
                      official_status,
                      legal_act_type,
                      hierarchy_of_the_legal_norm,
                      degree_of_revision,
                      vote_result_status,
                      vote_venue,
                      vote_trigger,
                      vote_trigger_actor,
                      vote_trigger_state_level,
                      vote_trigger_number,
                      vote_trigger_time,
                      turnout_quorum,
                      decision_quorum,
                      referendum_text_options,
                      counter_proposal,
                      institutional_precondition,
                      institutional_precondition_decision,
                      institutional_precondition_decision_actor,
                      action,
                      special_topics,
                      excluded_topics,
                      national_council_yes,
                      national_council_no,
                      national_council_abstentions,
                      states_council_yes,
                      states_council_no,
                      states_council_abstentions,
                      recommendation,
                      states_yes,
                      states_no,
                      remarks,
                      tags,
                      files,
                      archive)
  },
  .use_cache = use_cache,
  .cache_lifespan = cache_lifespan,
  .pkg = pkg)
}

#' Search in English referendum titles
#'
#' Allows to use the C2D API's primitive search functionality. The search is not case-sensitive and no [fuzzy
#' search](https://en.wikipedia.org/wiki/Approximate_string_matching) is performed (i.e. only exact matches are returned).
#'
#' Note that this function is probably not of much use since it doesn't return any additional information about the matched referendums but only the English
#' titles.
#'
#' @param term The Search term. A character scalar.
#'
#' @return A character vector of English referendum titles matching the search `term`.
#' @export
#'
#' @examples
#' search_referendums("freedom")
search_referendums <- function(term) {
  
  httr::RETRY(verb = "GET",
              url = "https://services.c2d.ch/referendums",
              query = list(mode = "search",
                           term = checkmate::assert_string(term)),
              config = httr_config(),
              times = 5L) %>%
    httr::content(as = "parsed") %$%
    items %>%
    purrr::flatten_chr() 
}
