# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/c2d.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literature programming approach used applying the R Markdown format.

utils::globalVariables(names = c(".",
                                 "items"))

.onLoad <- function(libname, pkgname) {
  pkgpins::clear(pkg = pkgname,
                 max_age = getOption("c2d.max_cache_lifespan",
                                     default = "30 days"))
}

.onUnload <- function(libpath) {
  pkgpins::deregister(pkg = pkg)
}

pkg <- utils::packageName()

httr_config <- function() {
  
  httr::config(cainfo = system.file("certs", "3479778542.crt",
                                    package = pkg,
                                    mustWork = TRUE))
}

#' Test C2D API availability
#'
#' Checks if the C2D API server is online and operational.
#'
#' @param quiet Whether to suppress printing a warning in case the API is unavailable.
#'
#' @return A logical scalar.
#' @export
is_online <- function(quiet = FALSE) {
  
  result <- FALSE
  response <- rlang::with_handlers(.expr = httr::RETRY(verb = "GET",
                                                       url = "https://services.c2d.ch/health",
                                                       config = httr_config(),
                                                       times = 5L),
                                   error = ~ paste0("Error: ", .x$message))
  
  if (class(response) == "response") {
    
    response %<>% httr::content(as = "parsed",
                                encoding = "UTF-8")
    
    if (response == "OK") {
      result <- TRUE
      
    } else if (checkmate::assert_flag(quiet)) {
      warning(glue::glue("C2D API server responded with '{response}'"),
              call. = FALSE,
              immediate. = TRUE)
    }
  }
  
  result
}

#' Get referendum data
#'
#' Downloads the complete data about all referendums covered by the C2D Database.
#'
#' Currently, this function only allows to download the C2D referendums database in its entirety.
#'
#' @param use_cache `r pkgsnip::param_label("use_cache")`
#' @param cache_lifespan `r pkgsnip::param_label("cache_lifespan")`
#' @param incl_drafts Whether or not to include referendum entries with _draft_ status in the returned data.
#'
#' @return `r pkgsnip::return_label("data")`
#' @export
referendums <- function(use_cache = TRUE,
                        cache_lifespan = "1 week",
                        incl_drafts = FALSE) {
  
  pkgpins::with_cache(.fn = ~ {
    
    # retrieve data
    data <-
      httr::RETRY(verb = "GET",
                  url = "https://services.c2d.ch/referendums",
                  query = list(mode = "stream",
                               format = "json"),
                  config = httr_config(),
                  times = 5L) %>%
      httr::content(as = "parsed") %$%
      items %>%
      # wrap all array fields in another list level for subsequent conversion to tibble
      purrr::map(.f = ~ .x %>% purrr::modify_if(.p = ~ length(.x) != 1L,
                                                .f = ~ list(.x))) %>%
      # convert to tibble
      dplyr::bind_rows()
    
    # check integrity
    ## ensure there's always exactly *one* `oid` per row
    ids <- data$`_id` %>% purrr::map(length)
    
    if (length(unique(names(ids))) != 1L ||
        !"$oid" %in% unique(names(ids)) ||
        any(purrr::flatten_int(unique(ids))) != 1L) {
      
      rlang::abort("Unexpected ID fields detected. Please debug.")
    }
    
    ## ensure `oid`s are unique
    if (data$`_id` %>%
        purrr::flatten_chr() %>%
        unique() %>%
        length() %>%
        magrittr::equals(nrow(data)) %>%
        magrittr::not()) {
      
      rlang::abort("Duplicated `oid`s detected. Please debug.")
    }
    
    # tidy data
    data %<>%
      # unnest `context`, `categories` and `title` (no technical need to be nested)
      tidyr::unnest_wider(col = context) %>%
      tidyr::unnest_wider(col = categories) %>%
      tidyr::unnest_wider(col = title,
                          names_sep = "_") %>%
      # rename variables
      dplyr::rename(created_datetime = created_on,
                    has_urgent_legal_basis = legal_act_type,
                    id = `_id`,
                    is_binding = vote_result_status,
                    is_counter_proposal = counter_proposal,
                    is_draft = draft,
                    legal_basis_type = official_status,
                    object_author = author_of_the_vote_object,
                    object_legal_level = hierarchy_of_the_legal_norm,
                    object_type = vote_object,
                    subnational_entity = canton,
                    trigger_actor = vote_trigger_actor,
                    trigger_state_level = vote_trigger_state_level,
                    trigger_threshold = vote_trigger_number,
                    trigger_time_limit = vote_trigger_time,
                    trigger_type = vote_trigger,
                    type = institution) %>%
      # recode variables
      dplyr::mutate(
        # flatten unnecessarily convoluted list columns
        dplyr::across(c(id,
                        action,
                        excluded_topics,
                        special_topics,
                        tags),
                      ~ .x %>% purrr::map(unlist)),
        # replace empty lists with `NULL` in list columns
        dplyr::across(where(is.list),
                      ~ dplyr::case_when(.x %>% purrr::map_lgl(~ length(.x) == 0L) ~ list(NULL),
                                         TRUE ~ .x)),
        # use explicit NA values
        dplyr::across(where(is.integer),
                      ~ dplyr::if_else(.x %in% c(-1L, -2L), NA_integer_, .x)),
        dplyr::across(where(is.character),
                      ~ dplyr::if_else(.x == "", NA_character_, .x)),
        # convert values to all-lowercase
        dplyr::across(c(legal_basis_type,
                        level,
                        object_author,
                        object_legal_level,
                        object_type,
                        result,
                        trigger_actor,
                        trigger_state_level,
                        trigger_type,
                        type),
                      stringr::str_to_lower),
        
        # specific recodings
        ## binary (dummies)
        is_binding = dplyr::case_when(is_binding == "Binding" ~ TRUE,
                                      is_binding == "Non-binding" ~ FALSE,
                                      TRUE ~ NA),
        is_counter_proposal = dplyr::case_when(is_counter_proposal == "Yes" ~ TRUE,
                                               is_counter_proposal == "No" ~ FALSE,
                                               TRUE ~ NA),
        has_urgent_legal_basis = dplyr::case_when(has_urgent_legal_basis == "Urgent" ~ TRUE,
                                                  has_urgent_legal_basis == "Normal" ~ FALSE,
                                                  TRUE ~ NA),
        ## nominal
        id = purrr::flatten_chr(id),
        level = stringr::str_replace(string = level,
                                     pattern = "sub-national",
                                     replacement = "subnational"),
        type = type %>% dplyr::recode("citizen assembly" = "citizens' assembly",
                                      "not provided" = NA_character_),
        trigger_actor = trigger_actor %>% dplyr::recode(institution = "other institution"),
        object_type = stringr::str_replace_all(string = object_type,
                                               pattern = c("ausformulierter vorschlag" = "formulated proposal",
                                                           "allg. anregung" = "general proposal")),
        ## ordinal
        ## interval
        created_datetime = purrr::flatten_dbl(created_datetime) %>% magrittr::divide_by(1000L) %>% lubridate::as_datetime()
      ) %>%
      # reorder columns
      dplyr::relocate(id,
                      is_draft,
                      country_code,
                      country_name,
                      subnational_entity,
                      municipality,
                      level,
                      type,
                      date,
                      created_datetime,
                      starts_with("title_"),
                      total_electorate,
                      citizens_abroad,
                      votes_yes,
                      votes_no,
                      votes_empty,
                      votes_invalid,
                      votes_per_canton,
                      result,
                      committee_name,
                      number, # TODO: Find out what this is!
                      object_type,
                      object_author,
                      object_legal_level,
                      legal_basis_type,
                      has_urgent_legal_basis,
                      degree_of_revision,
                      is_binding,
                      is_counter_proposal,
                      vote_venue,
                      starts_with("trigger_"),
                      turnout_quorum,
                      decision_quorum,
                      referendum_text_options,
                      institutional_precondition,
                      institutional_precondition_decision,
                      institutional_precondition_decision_actor,
                      action,
                      special_topics,
                      excluded_topics,
                      national_council_yes,
                      national_council_no,
                      national_council_abstentions,
                      states_council_yes,
                      states_council_no,
                      states_council_abstentions,
                      recommendation,
                      states_yes,
                      states_no,
                      remarks,
                      tags,
                      files,
                      archive) %>%
      purrr::when(incl_drafts ~ .,
                  ~ dplyr::filter(.data = ., !is_draft))
  },
  .use_cache = use_cache,
  .cache_lifespan = cache_lifespan,
  .pkg = pkg)
}

#' Search in English referendum titles
#'
#' Allows to use the C2D API's primitive search functionality. The search is not case-sensitive and no [fuzzy
#' search](https://en.wikipedia.org/wiki/Approximate_string_matching) is performed (i.e. only exact matches are returned).
#'
#' Note that this function is probably not of much use since it doesn't return any additional information about the matched referendums but only the English
#' titles.
#'
#' @param term The Search term. A character scalar.
#'
#' @return A character vector of English referendum titles matching the search `term`.
#' @export
#'
#' @examples
#' search_referendums("freedom")
search_referendums <- function(term) {
  
  httr::RETRY(verb = "GET",
              url = "https://services.c2d.ch/referendums",
              query = list(mode = "search",
                           term = checkmate::assert_string(term)),
              config = httr_config(),
              times = 5L) %>%
    httr::content(as = "parsed") %$%
    items %>%
    purrr::flatten_chr() 
}
